### ISSUE TITLE
Lang selector should be reworked and made accessible

### ISSUE THREAD

**Issue by ghost** [poppy-project/poppy-project.org#11]
Refers to #9.

Language selector should be made more easy to access for the users, unless we can redirect them to the right language section.

Since this should remain a secondary action, the very top-right area seems the best place for these.

Also, flags represent countries, not languages. These should be removed in favor of a list of available languages.

**Comment by ghost** [comment]
This is a quick implementation but it seems rather decent to get on first version.

<img width="437" alt="lang-switch-wip" src="https://cloud.githubusercontent.com/assets/37416/15098951/14623d96-154a-11e6-8b49-f7f328c066fb.png">

@jgrizou is that what you had in mind?

**Comment by matthieu-lapeyre** [comment]
I would prefer not to mix content and site feature. For me it should in the top corner or bottom corner not in the menu. Maybe just add eng | fra to avoir flag                                                                                                                                                                                                                                                                                                                                                                                                                                  De:notifications@github.comEnvoyé:8 mai 2016 6:25 PMÀ:poppy-project.org@noreply.github.comRépondre à:reply@reply.github.comObjet:Re: [poppy-project/poppy-project.org] Lang selector should be reworked and made accessible (#11)  This is a quick implementation but it seems rather decent to get on first version.

@jgrizou is that what you had in mind?

—You are receiving this because you are subscribed to this thread.Reply to this email directly or view it on GitHub

**Comment by ghost** [comment]
Adding another layer of content on top of the menu occupies much space for very little amount of text.
This is gets even worse as the screen resolution grows big.

<img width="1026" alt="icanhazemptypixls" src="https://cloud.githubusercontent.com/assets/37416/15099321/81151b04-1552-11e6-91f9-6a9f8a4b6751.png">

To avoid this, I can only think of: 
- Moving the component next to the main navigation items and have it somehow stand out: icon, add space around...
- Moving the component to the footer and consider it is not a main navigation item.

From what @jgrizou said, this may be a key feature, therefore having it at the top of the pages doesn't seem wrong.

Anyway, I got it stand out a bit, and it is be the best compromise I could think of so far.

<img width="1280" alt="chineseforthebraves" src="https://cloud.githubusercontent.com/assets/37416/15099355/76444988-1553-11e6-88ef-a1313021e9d5.png">

**Comment by jgrizou** [comment]
Yes, that is what I had in mind. I prefer the second version with the current language displayed and a dropdown to select another.

Top right is the most intuitive way to me. I would never scroll down to check if other languages are available. Also, as far as I recall, language selection is always top-right on other websites.

As for the github/twitter/youtube bar, I think in the footer is fine. We should aim at providing the links to specific youtube videos or github repos in the pages when needed.

**Comment by ghost** [comment]
I consider this is enough for the first release, we can think about something else later.

Fixed by 299e2f9
